language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6.0"
  - "3.6.1"
  - "3.6.2"
  - "3.6.3"
  - "3.6.4"
  - "3.6.5"
  - "3.6.6"
  - "3.7"
  - "pypy"
sudo: false
install:
  - bash scripts/install.sh
script:
  - python scripts/run-tests.py
after_success:
  - python-codacy-coverage -r coverage.xml
